version: '3'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:12.0.2
    container_name: keycloak
    environment:
      KEYCLOAK_USER: 'admin'
      KEYCLOAK_PASSWORD: 'admin'
    command:
      - -Djboss.http.port=8080
    ports:
      - 8080:8080
    networks:
      - app
  app:
    container_name: app
    build:
      context: .
    networks:
      - app
  oauth2proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v6.1.1
    container_name: oauth2proxy
    environment:
      OAUTH2_PROXY_HTTP_ADDRESS: 0.0.0.0:5001
      OAUTH2_PROXY_UPSTREAMS: http://app:5000
      OAUTH2_PROXY_CLIENT_ID: flask-oidc
      OAUTH2_PROXY_CLIENT_SECRET: todo
      OAUTH2_PROXY_COOKIE_SECRET: oGr24sDKy4VyDw14DQqtiTXGzb6viyFk
      OAUTH2_PROXY_COOKIE_SECURE: 'false'
      OAUTH2_PROXY_COOKIE_EXPIRE: 5m
      OAUTH2_PROXY_SCOPE: "openid profile"
      OAUTH2_PROXY_COOKIE_REFRESH: 1m
      OAUTH2_PROXY_EMAIL_DOMAINS: '*'
      OAUTH2_PROXY_PROVIDER: oidc
      OAUTH2_PROXY_PROVIDER_DISPLAY_NAME: Keycloak
      OAUTH2_PROXY_SKIP_OIDC_DISCOVERY: 'true'
      OAUTH2_PROXY_OIDC_ISSUER_URL: http://keycloak:8080/auth/realms/master
      OAUTH2_PROXY_LOGIN_URL: http://keycloak:8080/auth/realms/master/protocol/openid-connect/auth
      OAUTH2_PROXY_REDEEM_URL: http://keycloak:8080/auth/realms/master/protocol/openid-connect/token
      OAUTH2_PROXY_VALIDATE_URL: http://keycloak:8080/auth/realms/master/protocol/openid-connect/userinfo
      OAUTH2_PROXY_OIDC_JWKS_URL: http://keycloak:8080/auth/realms/master/protocol/openid-connect/certs
      OAUTH2_PROXY_REDIRECT_URL: http://localhost:5000/oauth2/callback
      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: 'true'
      OAUTH2_PROXY_PASS_ACCESS_TOKEN: 'true'
    networks:
      - app
    ports:
      - 5000:5001

networks:
  app: